export const mockRowData = [
  { id: 1, programm: "Wanda", recYear: 2008, educDir: "Cincinnati" },
  { id: 2, programm: "Sher", recYear: 2000, educDir: "Quincy" },
  { id: 3, programm: "Malory", recYear: 2013, educDir: "Alldays" },
  { id: 4, programm: "Jayson", recYear: 1995, educDir: "Batesville" },
  { id: 5, programm: "Jae", recYear: 1996, educDir: "Liberal" },
  { id: 6, programm: "Ronica", recYear: 1985, educDir: "Qeqertarsuaq Airport" },
  { id: 7, programm: "Matthias", recYear: 2003, educDir: "La Môle" },
  { id: 8, programm: "Francisca", recYear: 1999, educDir: "Gasuke" },
  { id: 9, programm: "Dalt", recYear: 1994, educDir: "American River" },
  { id: 10, programm: "Almeta", recYear: 1997, educDir: "Oxford House" },
  { id: 11, programm: "Tabb", recYear: 1998, educDir: "Tuscaloosa" },
  { id: 13, programm: "Bethanne", recYear: 2011, educDir: "Sumter" },
  { id: 14, programm: "Hilario", recYear: 2006, educDir: "Ben Slimane" },
  { id: 15, programm: "Venita", recYear: 2011, educDir: "Odate" },
  { id: 16, programm: "Cassey", recYear: 2005, educDir: "Camp Pohakuloa" },
  { id: 17, programm: "Winonah", recYear: 2006, educDir: "Boise" },
  { id: 18, programm: "Willette", recYear: 2006, educDir: "Minvoul" },
  { id: 19, programm: "Erv", recYear: 2006, educDir: "Bainbridge" },
  { id: 20, programm: "Ferdinand", recYear: 2010, educDir: "Pastos Bons" },
  { id: 21, programm: "Eleanora", recYear: 2005, educDir: "Bemichi" },
  { id: 22, programm: "Eleonore", recYear: 2008, educDir: "Seal Bay" },
  { id: 23, programm: "Rocky", recYear: 1989, educDir: "Pore" },
  { id: 24, programm: "Chloe", recYear: 1984, educDir: "Fajardo" },
  { id: 25, programm: "Jaclin", recYear: 1997, educDir: "Ghardaïa" },
  { id: 26, programm: "Olivie", recYear: 2010, educDir: "Greenville" },
  { id: 28, programm: "Benyamin", recYear: 1985, educDir: "Prince Rupert" },
  { id: 29, programm: "Tonnie", recYear: 2000, educDir: "Patras" },
  { id: 30, programm: "Selia", recYear: 2008, educDir: "Erbogachen" },
  {
    id: 32,
    programm: "Berti",
    recYear: 1998,
    educDir: "Military Camp Number 2-D",
  },
  { id: 33, programm: "Arny", recYear: 1996, educDir: "Centralia" },
  { id: 34, programm: "Claudius", recYear: 2001, educDir: "Avarua" },
  { id: 35, programm: "Kirsteni", recYear: 2005, educDir: "Houma" },
  { id: 36, programm: "Maurise", recYear: 1990, educDir: "Bahia Blanca" },
  { id: 37, programm: "Booth", recYear: 2006, educDir: "Orapa" },
  { id: 38, programm: "Hunt", recYear: 1993, educDir: "Bangkok" },
  { id: 39, programm: "Doro", recYear: 1998, educDir: "Yalgoo" },
  { id: 40, programm: "Eal", recYear: 1990, educDir: "Aguni" },
  { id: 41, programm: "Tera", recYear: 2006, educDir: "Manizales" },
  { id: 42, programm: "Haven", recYear: 2000, educDir: "Kleinsee" },
  { id: 43, programm: "Lyell", recYear: 1991, educDir: "Sevierville" },
  { id: 44, programm: "Riane", recYear: 1996, educDir: "Johnston Atoll" },
  { id: 45, programm: "Myer", recYear: 1992, educDir: "Orange/Caritat" },
  { id: 46, programm: "Calley", recYear: 2001, educDir: "Anatom Island" },
  { id: 47, programm: "Genni", recYear: 2002, educDir: "Chifeng" },
  { id: 48, programm: "Darline", recYear: 1988, educDir: "Vasco da Gama" },
  { id: 49, programm: "Rowe", recYear: 1985, educDir: "Rajahmundry" },
  { id: 50, programm: "Devon", recYear: 1992, educDir: "Bowling Green" },
  { id: 51, programm: "Mort", recYear: 2009, educDir: "Surallah" },
  { id: 52, programm: "Doug", recYear: 1995, educDir: "Queens" },
  { id: 53, programm: "Jill", recYear: 2001, educDir: "Seinäjoki / Ilmajoki" },
  { id: 54, programm: "Tiebold", recYear: 1989, educDir: "Uvol" },
  { id: 57, programm: "Xenos", recYear: 1999, educDir: "Alligandi" },
  { id: 58, programm: "Tera", recYear: 1984, educDir: "Kasama" },
  { id: 59, programm: "Mac", recYear: 1999, educDir: "Kodiak" },
  { id: 60, programm: "Sylvia", recYear: 1995, educDir: "Musina" },
  { id: 61, programm: "Ursala", recYear: 1992, educDir: "Kasaba Bay" },
  { id: 62, programm: "Amabelle", recYear: 2007, educDir: "Pico Island" },
  { id: 63, programm: "Gabby", recYear: 2000, educDir: "Rebun" },
  { id: 64, programm: "Vinni", recYear: 2002, educDir: "Rokot-Sumatra Island" },
  { id: 65, programm: "Sinclare", recYear: 2008, educDir: "Araguaína" },
  { id: 66, programm: "Jonah", recYear: 1994, educDir: "Pompano Beach" },
  { id: 67, programm: "Vivienne", recYear: 1992, educDir: "Lagos de Moreno" },
  { id: 68, programm: "Abdul", recYear: 2006, educDir: "Årø" },
  { id: 70, programm: "Nicolis", recYear: 2005, educDir: "Svetlaya" },
  { id: 71, programm: "Alexis", recYear: 2008, educDir: "Austin" },
  { id: 72, programm: "Jessey", recYear: 2007, educDir: "Danville" },
  { id: 74, programm: "Marwin", recYear: 1989, educDir: "Hateruma" },
  { id: 75, programm: "Sabina", recYear: 1992, educDir: "Dallas-Fort Worth" },
  { id: 77, programm: "Jase", recYear: 2001, educDir: "April River" },
  { id: 78, programm: "Urbano", recYear: 2010, educDir: "Franklin" },
  { id: 79, programm: "Amara", recYear: 2007, educDir: "Vadsø" },
  { id: 80, programm: "Domini", recYear: 1991, educDir: "Daggett" },
  { id: 81, programm: "Fin", recYear: 1996, educDir: "Edenton" },
  { id: 82, programm: "Berty", recYear: 2000, educDir: "Rafaela" },
  { id: 83, programm: "Elset", recYear: 2004, educDir: "Bowman" },
  { id: 86, programm: "Charmaine", recYear: 1997, educDir: "Skikda" },
  { id: 87, programm: "Mirabella", recYear: 2005, educDir: "Chandalar Lake" },
  { id: 88, programm: "Yurik", recYear: 2005, educDir: "Hilton Head Island" },
  { id: 89, programm: "Galven", recYear: 1999, educDir: "Juneau" },
  { id: 90, programm: "Kinsley", recYear: 2008, educDir: "Shageluk" },
  { id: 91, programm: "Trey", recYear: 2007, educDir: "Hibbing" },
  { id: 92, programm: "Johannah", recYear: 1996, educDir: "Fetlar Island" },
  { id: 93, programm: "Clovis", recYear: 2011, educDir: "Norsup" },
  { id: 94, programm: "Hubey", recYear: 2003, educDir: "Memphis" },
  { id: 95, programm: "Janella", recYear: 1962, educDir: "Iqaluit" },
  { id: 96, programm: "Antone", recYear: 2011, educDir: "Mobile" },
  { id: 97, programm: "Rahel", recYear: 2004, educDir: "Simberi Island" },
  { id: 98, programm: "Lazarus", recYear: 1993, educDir: "Agen/La Garenne" },
  { id: 100, programm: "Bevan", recYear: 2012, educDir: "Milton" },
];
