export const mockRowData = [
  {
    id: 1,
    programm: "Прикладная математика и информатика (01.03.02)",
    recYear: 2022,
    educLvl: "Бакалавр",
    educDir: "Jabbersphere",
  },
  {
    id: 2,
    programm: "Прикладная математика и информатика (01.04.02)",
    recYear: 2019,
    educLvl: "Магистратура",
    educDir: "Livepath",
  },
  {
    id: 3,
    programm:
      "Фундаментальная информатика и информационные технологии (02.03.02)",
    recYear: 2018,
    educLvl: "Магистратура",
    educDir: "Mydeo",
  },
  {
    id: 4,
    programm: "Физика (03.03.02)",
    recYear: 2021,
    educLvl: "Бакалавр",
    educDir: "Skimia",
  },
  {
    id: 5,
    programm: "Физика (03.04.02",
    recYear: 2019,
    educLvl: "Магистратура",
    educDir: "Gigaclub",
  },
  {
    id: 6,
    programm: "Lotstring",
    recYear: 2003,
    educLvl: "Bak",
    educDir: "Centimia",
  },
  {
    id: 7,
    programm: "Overhold",
    recYear: 1999,
    educLvl: "Mag",
    educDir: "Dazzlesphere",
  },
  {
    id: 8,
    programm: "Opela",
    recYear: 1998,
    educLvl: "Mag",
    educDir: "Skimia",
  },
  {
    id: 9,
    programm: "Daltfresh",
    recYear: 1985,
    educLvl: "Bak",
    educDir: "Quinu",
  },
  {
    id: 10,
    programm: "Temp",
    recYear: 2013,
    educLvl: "Bak",
    educDir: "Zoonoodle",
  },
  {
    id: 11,
    programm: "Latlux",
    recYear: 1985,
    educLvl: "Bak",
    educDir: "Fanoodle",
  },
  {
    id: 12,
    programm: "Pannier",
    recYear: 2000,
    educLvl: "Mag",
    educDir: "Flashset",
  },
  {
    id: 13,
    programm: "Fintone",
    recYear: 1995,
    educLvl: "Bak",
    educDir: "Flashset",
  },
  {
    id: 14,
    programm: "Latlux",
    recYear: 1996,
    educLvl: "Mag",
    educDir: "Jayo",
  },
  {
    id: 15,
    programm: "Fintone",
    recYear: 2007,
    educLvl: "Bak",
    educDir: "Abata",
  },
  {
    id: 16,
    programm: "Fintone",
    recYear: 2010,
    educLvl: "Bak",
    educDir: "Avaveo",
  },
  {
    id: 17,
    programm: "Tresom",
    recYear: 1993,
    educLvl: "Mag",
    educDir: "Edgetag",
  },
  {
    id: 18,
    programm: "Andalax",
    recYear: 1968,
    educLvl: "Mag",
    educDir: "Npath",
  },
  {
    id: 19,
    programm: "Fix San",
    recYear: 1991,
    educLvl: "Bak",
    educDir: "Jaxspan",
  },
  {
    id: 20,
    programm: "Bitchip",
    recYear: 2007,
    educLvl: "Bak",
    educDir: "Fivebridge",
  },
  {
    id: 21,
    programm: "Y-Solowarm",
    recYear: 1986,
    educLvl: "Bak",
    educDir: "Topdrive",
  },
  {
    id: 22,
    programm: "Trippledex",
    recYear: 1989,
    educLvl: "Bak",
    educDir: "Layo",
  },
  {
    id: 23,
    programm: "Flowdesk",
    recYear: 2010,
    educLvl: "Bak",
    educDir: "Eayo",
  },
  {
    id: 24,
    programm: "Rank",
    recYear: 2004,
    educLvl: "Bak",
    educDir: "Thoughtbridge",
  },
  {
    id: 25,
    programm: "Ventosanzap",
    recYear: 1988,
    educLvl: "Bak",
    educDir: "Topicblab",
  },
  {
    id: 26,
    programm: "Asoka",
    recYear: 1991,
    educLvl: "Mag",
    educDir: "Tambee",
  },
  {
    id: 27,
    programm: "Voltsillam",
    recYear: 1992,
    educLvl: "Bak",
    educDir: "Zoovu",
  },
  {
    id: 28,
    programm: "Daltfresh",
    recYear: 2004,
    educLvl: "Mag",
    educDir: "Jamia",
  },
  {
    id: 29,
    programm: "Zontrax",
    recYear: 1992,
    educLvl: "Bak",
    educDir: "Camido",
  },
  {
    id: 30,
    programm: "Domainer",
    recYear: 2002,
    educLvl: "Mag",
    educDir: "Voolith",
  },
  {
    id: 31,
    programm: "Fintone",
    recYear: 1995,
    educLvl: "Mag",
    educDir: "Skajo",
  },
  {
    id: 32,
    programm: "Zamit",
    recYear: 2006,
    educLvl: "Bak",
    educDir: "Quimm",
  },
  {
    id: 33,
    programm: "Voyatouch",
    recYear: 2009,
    educLvl: "Bak",
    educDir: "Eidel",
  },
  {
    id: 34,
    programm: "Y-find",
    recYear: 1991,
    educLvl: "Mag",
    educDir: "Cogilith",
  },
  {
    id: 35,
    programm: "Aerified",
    recYear: 1985,
    educLvl: "Bak",
    educDir: "Skibox",
  },
  {
    id: 36,
    programm: "Domainer",
    recYear: 1996,
    educLvl: "Bak",
    educDir: "Vimbo",
  },
  {
    id: 37,
    programm: "Voyatouch",
    recYear: 2004,
    educLvl: "Mag",
    educDir: "Vimbo",
  },
  {
    id: 38,
    programm: "Alpha",
    recYear: 1997,
    educLvl: "Mag",
    educDir: "Dynazzy",
  },
  {
    id: 39,
    programm: "Cardguard",
    recYear: 2000,
    educLvl: "Mag",
    educDir: "Mycat",
  },
  {
    id: 40,
    programm: "Sub-Ex",
    recYear: 2003,
    educLvl: "Bak",
    educDir: "Zoomzone",
  },
  {
    id: 41,
    programm: "Bytecard",
    recYear: 2001,
    educLvl: "Mag",
    educDir: "Fanoodle",
  },
  {
    id: 42,
    programm: "Tresom",
    recYear: 2001,
    educLvl: "Bak",
    educDir: "Zoozzy",
  },
  {
    id: 43,
    programm: "Wrapsafe",
    recYear: 1998,
    educLvl: "Bak",
    educDir: "Thoughtblab",
  },
  {
    id: 44,
    programm: "Y-Solowarm",
    recYear: 1999,
    educLvl: "Mag",
    educDir: "Zoomdog",
  },
  {
    id: 45,
    programm: "Vagram",
    recYear: 2006,
    educLvl: "Mag",
    educDir: "Zoonder",
  },
  {
    id: 46,
    programm: "Mat Lam Tam",
    recYear: 2009,
    educLvl: "Mag",
    educDir: "Zoomcast",
  },
  {
    id: 47,
    programm: "Latlux",
    recYear: 2005,
    educLvl: "Mag",
    educDir: "Izio",
  },
  {
    id: 48,
    programm: "Overhold",
    recYear: 2013,
    educLvl: "Mag",
    educDir: "Eare",
  },
  {
    id: 49,
    programm: "Y-find",
    recYear: 2007,
    educLvl: "Mag",
    educDir: "Skyvu",
  },
  {
    id: 50,
    programm: "Pannier",
    recYear: 2012,
    educLvl: "Mag",
    educDir: "Zoomlounge",
  },
  {
    id: 51,
    programm: "Tres-Zap",
    recYear: 2012,
    educLvl: "Mag",
    educDir: "Rooxo",
  },
  {
    id: 52,
    programm: "Duobam",
    recYear: 1986,
    educLvl: "Bak",
    educDir: "Chatterpoint",
  },
  {
    id: 53,
    programm: "Trippledex",
    recYear: 2011,
    educLvl: "Mag",
    educDir: "Thoughtsphere",
  },
  {
    id: 54,
    programm: "Mat Lam Tam",
    recYear: 2001,
    educLvl: "Bak",
    educDir: "Zazio",
  },
  {
    id: 55,
    programm: "Greenlam",
    recYear: 1999,
    educLvl: "Bak",
    educDir: "Yata",
  },
  {
    id: 56,
    programm: "Fix San",
    recYear: 1997,
    educLvl: "Bak",
    educDir: "Photofeed",
  },
  {
    id: 57,
    programm: "Zathin",
    recYear: 2004,
    educLvl: "Bak",
    educDir: "Tagchat",
  },
  {
    id: 58,
    programm: "Namfix",
    recYear: 1986,
    educLvl: "Bak",
    educDir: "Devpulse",
  },
  {
    id: 59,
    programm: "Zontrax",
    recYear: 1992,
    educLvl: "Bak",
    educDir: "Skiba",
  },
  {
    id: 60,
    programm: "Redhold",
    recYear: 2000,
    educLvl: "Mag",
    educDir: "Devcast",
  },
  {
    id: 61,
    programm: "Toughjoyfax",
    recYear: 2008,
    educLvl: "Bak",
    educDir: "Layo",
  },
  {
    id: 62,
    programm: "Asoka",
    recYear: 2012,
    educLvl: "Mag",
    educDir: "Zoonoodle",
  },
  {
    id: 63,
    programm: "Aerified",
    recYear: 2009,
    educLvl: "Bak",
    educDir: "Kwinu",
  },
  {
    id: 64,
    programm: "Asoka",
    recYear: 2007,
    educLvl: "Bak",
    educDir: "Layo",
  },
  {
    id: 65,
    programm: "Biodex",
    recYear: 1990,
    educLvl: "Bak",
    educDir: "Meedoo",
  },
  {
    id: 66,
    programm: "Keylex",
    recYear: 2003,
    educLvl: "Mag",
    educDir: "Agimba",
  },
  {
    id: 67,
    programm: "Treeflex",
    recYear: 2007,
    educLvl: "Mag",
    educDir: "Abata",
  },
  {
    id: 68,
    programm: "Bamity",
    recYear: 2000,
    educLvl: "Mag",
    educDir: "Jatri",
  },
  {
    id: 69,
    programm: "Redhold",
    recYear: 2001,
    educLvl: "Bak",
    educDir: "Miboo",
  },
  {
    id: 70,
    programm: "Aerified",
    recYear: 2005,
    educLvl: "Bak",
    educDir: "Voonix",
  },
  {
    id: 71,
    programm: "Voyatouch",
    recYear: 1996,
    educLvl: "Bak",
    educDir: "Voonte",
  },
  {
    id: 72,
    programm: "Tin",
    recYear: 1996,
    educLvl: "Mag",
    educDir: "Zoombeat",
  },
  {
    id: 73,
    programm: "Bigtax",
    recYear: 2003,
    educLvl: "Mag",
    educDir: "Innotype",
  },
  {
    id: 74,
    programm: "Voltsillam",
    recYear: 2009,
    educLvl: "Bak",
    educDir: "Lazzy",
  },
  {
    id: 75,
    programm: "Job",
    recYear: 1994,
    educLvl: "Bak",
    educDir: "Buzzbean",
  },
  {
    id: 76,
    programm: "Cardify",
    recYear: 2005,
    educLvl: "Mag",
    educDir: "Agimba",
  },
  {
    id: 77,
    programm: "Flexidy",
    recYear: 2004,
    educLvl: "Mag",
    educDir: "Mudo",
  },
  {
    id: 78,
    programm: "Voltsillam",
    recYear: 2002,
    educLvl: "Mag",
    educDir: "Topiczoom",
  },
  {
    id: 79,
    programm: "Stim",
    recYear: 2002,
    educLvl: "Bak",
    educDir: "Zoomcast",
  },
  {
    id: 80,
    programm: "Domainer",
    recYear: 2001,
    educLvl: "Mag",
    educDir: "Fiveclub",
  },
  {
    id: 81,
    programm: "Sub-Ex",
    recYear: 2009,
    educLvl: "Mag",
    educDir: "Jabberbean",
  },
  {
    id: 82,
    programm: "Tin",
    recYear: 1994,
    educLvl: "Bak",
    educDir: "Ainyx",
  },
  {
    id: 83,
    programm: "Fixflex",
    recYear: 1991,
    educLvl: "Bak",
    educDir: "Edgepulse",
  },
  {
    id: 84,
    programm: "Fintone",
    recYear: 1985,
    educLvl: "Bak",
    educDir: "Oba",
  },
  {
    id: 85,
    programm: "Trippledex",
    recYear: 1995,
    educLvl: "Bak",
    educDir: "Demimbu",
  },
  {
    id: 86,
    programm: "Regrant",
    recYear: 2001,
    educLvl: "Bak",
    educDir: "Feedspan",
  },
  {
    id: 87,
    programm: "Bigtax",
    recYear: 1996,
    educLvl: "Mag",
    educDir: "Nlounge",
  },
  {
    id: 88,
    programm: "Ventosanzap",
    recYear: 1993,
    educLvl: "Bak",
    educDir: "Rhynyx",
  },
  {
    id: 89,
    programm: "Veribet",
    recYear: 1959,
    educLvl: "Bak",
    educDir: "Oyoyo",
  },
  {
    id: 90,
    programm: "Transcof",
    recYear: 1995,
    educLvl: "Bak",
    educDir: "Zoozzy",
  },
  {
    id: 91,
    programm: "Y-find",
    recYear: 2009,
    educLvl: "Mag",
    educDir: "Livefish",
  },
  {
    id: 92,
    programm: "Span",
    recYear: 1969,
    educLvl: "Bak",
    educDir: "Photolist",
  },
  {
    id: 93,
    programm: "Latlux",
    recYear: 1998,
    educLvl: "Mag",
    educDir: "Yodo",
  },
  {
    id: 94,
    programm: "Ventosanzap",
    recYear: 2007,
    educLvl: "Bak",
    educDir: "Mynte",
  },
  {
    id: 95,
    programm: "Biodex",
    recYear: 1994,
    educLvl: "Mag",
    educDir: "Abatz",
  },
  {
    id: 96,
    programm: "Zathin",
    recYear: 2003,
    educLvl: "Mag",
    educDir: "Twitterlist",
  },
  {
    id: 97,
    programm: "Cookley",
    recYear: 1980,
    educLvl: "Mag",
    educDir: "Gabvine",
  },
  {
    id: 98,
    programm: "Job",
    recYear: 1987,
    educLvl: "Bak",
    educDir: "Babbleopia",
  },
  {
    id: 99,
    programm: "It",
    recYear: 2007,
    educLvl: "Bak",
    educDir: "Talane",
  },
  {
    id: 100,
    programm: "Tresom",
    recYear: 1995,
    educLvl: "Bak",
    educDir: "Meeveo",
  },
];
